[package]
name = "rig2-macros"
description = "The #[tool] attribute and #[derive(Embed)] for rig2."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
proc-macro-crate.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
